### ISSUE TITLE
Custom route issue on 10.0.4

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/bakery-app-starter-issues#16] opened 2018-09-03 12:47 UTC
Hi,
There is an issue on v 10.0.4 that was not present on 10.0.2.

V10.0.2
Use bakery application. Write a custom not managed route (for example sue dashboard1 instead of dashboard). You have the CustomRouteNotFoundError message

![image](https://user-images.githubusercontent.com/3224592/44920515-6cd1c880-ad40-11e8-82c9-9770c0c2a9f4.png)

Updating the Bakery app to 10.0.4 we have the error trace instead

![image](https://user-images.githubusercontent.com/3224592/44920634-be7a5300-ad40-11e8-9d31-ffcaeb363560.png)

The same code on Vaadin 10.0.2 works fine while using 10.0.4 give me the exception on the UI.

Something about exception handling broke off from 10.0.2 to 10.0.4

**Comment by gianluca-valentini** [comment] 2018-09-03 13:37
Thank you,
your java fix is perfect. However, my attempt was to point out that from 10.0.2 to 10.0.4 there seems to be a different handling of exceptions.

Because the same code has different result just changing the Vaadin version.
Thanks
Gianluca

**Comment by alvarezguille** [comment] 2018-09-03 14:28
I'm not sure if it's about handling of exceptions, or just that there was no exception before. 
Anyway it seems to be a regression and we'll take a deeper look. Thanks again.
I will close this issue once bakery starter with the fix is released. 
vaadin/vaadin-tabs-flow#72 can be used to track the underlying issue

**Comment by alvarezguille** [comment] 2018-09-04 15:17
`vaadin-tabs-flow version` `1.0.5` was released including a fix for the underlying issue. and the workaround of `hrefs.contains(href)` is not needed anymore.
Starter was updated to include Vaadin 10.0.5 and tabs 1.0.5 and is available in vaadin.com/start

**Closed by alvarezguille** 2018-09-04 15:17 UTC
